# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-09 21:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userAssociated', to=settings.AUTH_USER_MODEL),
        ),
    ]
