# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-09 21:50
from __future__ import unicode_literals

import Account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20200909_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to=Account.models.upload_update_image),
        ),
    ]
